import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export async function exportPdf(tools, userEmail) {
  const doc = new jsPDF({ orientation: 'landscape' })
  const date = new Date().toLocaleDateString()
  const dateStamp = new Date().toISOString().split('T')[0]

  // Header
  doc.setFontSize(18)
  doc.setTextColor(40)
  doc.text('ToolDB Collection Report', 14, 20)

  doc.setFontSize(10)
  doc.setTextColor(120)
  doc.text(`Generated: ${date}`, 14, 28)
  if (userEmail) {
    doc.text(`Account: ${userEmail}`, 14, 34)
  }

  // Table data
  const tableRows = tools.map((t) => [
    t.name || '',
    t.brand || '',
    t.model_number || '',
    t.serial_number || '',
    t.tool_type || '',
    t.purchase_date || '',
    t.purchase_price ? `$${parseFloat(t.purchase_price).toFixed(2)}` : '',
    t.retailer || '',
    t.condition || '',
  ])

  autoTable(doc, {
    startY: 40,
    head: [['Name', 'Brand', 'Model', 'Serial', 'Type', 'Purchase Date', 'Price', 'Retailer', 'Condition']],
    body: tableRows,
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [74, 144, 226],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
  })

  // Footer totals
  const total = tools.reduce((sum, t) => sum + (parseFloat(t.purchase_price) || 0), 0)
  const finalY = doc.lastAutoTable.finalY + 10

  doc.setFontSize(11)
  doc.setTextColor(40)
  doc.text(`Total Tools: ${tools.length}`, 14, finalY)
  doc.text(`Total Collection Value: $${total.toFixed(2)}`, 14, finalY + 7)

  doc.setFontSize(8)
  doc.setTextColor(160)
  doc.text('Generated by ToolDB — tooldb.app', 14, finalY + 16)

  doc.save(`tooldb-collection-${dateStamp}.pdf`)
}
